import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const accessDate = "2026-07-04";
const outputDir = "outputs";
const outputPath = `${outputDir}/乙游_情绪价值_情感消费_数字亲密关系_商学文献矩阵.xlsx`;

const matrixHeaders = [
  "paper_id",
  "中文定位",
  "题目",
  "作者",
  "年份",
  "期刊/来源",
  "期刊层级/用途",
  "DOI/稳定链接",
  "原文来源URL",
  "验证状态",
  "摘要",
  "关键词",
  "研究问题",
  "研究设计/方法",
  "使用数据/样本",
  "核心变量/构念",
  "研究贡献",
  "研究结论",
  "对本选题的用法",
  "局限/待注意",
  "下载状态",
  "版本/访问日期",
];

const matrixRows = [
  [
    "holbrook_hirschman_1982_experiential",
    "情绪价值/体验消费理论源头",
    "The Experiential Aspects of Consumption: Consumer Fantasies, Feelings, and Fun",
    "Morris B. Holbrook; Elizabeth C. Hirschman",
    1982,
    "Journal of Consumer Research",
    "消费者研究顶刊; 理论奠基",
    "10.1086/208906",
    "https://doi.org/10.1086/208906",
    "verified_primary",
    "文章主张消费者行为不能只用信息处理模型解释，需承认消费中的幻想、感受、乐趣、象征性、享乐性与审美性。",
    "experiential consumption; fantasies; feelings; fun; hedonic consumption; symbolic consumption",
    "消费是否不仅是理性信息处理，也包括幻想、情感和审美体验？",
    "概念/理论论文，提出体验消费视角并与信息处理模型对照。",
    "无一手调查样本；基于理论整合和概念框架。",
    "幻想; 感受; 乐趣; 象征消费; 享乐消费",
    "为“情绪价值”提供商学正当性：乙游消费不是功能性购买，而是以情绪、幻想、审美和叙事体验为核心的消费。",
    "消费体验由追求 fantasies, feelings, fun 驱动，体验性消费应成为消费者研究的重要对象。",
    "作为绪论和理论基础文献，定义乙游的消费属性：情绪/幻想/叙事体验产品。",
    "年代较早；没有数字平台和互动产品场景，需要与后续品牌体验/数字亲密文献结合。",
    "publisher page only; PDF behind access/purchase wall",
    `published version; accessed ${accessDate}`,
  ],
  [
    "babin_1994_hedonic_utilitarian",
    "情绪价值测量",
    "Work and/or Fun: Measuring Hedonic and Utilitarian Shopping Value",
    "Barry J. Babin; William R. Darden; Mitch Griffin",
    1994,
    "Journal of Consumer Research",
    "消费者研究顶刊; 量表/变量参考",
    "10.1086/209376",
    "https://doi.org/10.1086/209376",
    "verified_primary",
    "文章开发并验证了购物体验中享乐价值与功利价值的测量量表，证明二者是不同维度且与重要消费变量相关。",
    "hedonic value; utilitarian value; shopping value; scale development; consumer experience",
    "如何测量消费体验中的享乐价值和功利价值？二者是否为可区分维度？",
    "多步骤量表开发与验证。",
    "购物消费情境中的调查/量表验证数据；网页摘要未给出具体样本量。",
    "hedonic shopping value; utilitarian shopping value; consumption variables",
    "可作为“情绪价值/享乐价值”的测量基础，把乙游中的陪伴、愉悦、沉浸与功能性游戏收益区分开。",
    "享乐价值与功利价值是不同维度，并与一系列消费结果相关。",
    "用于构建问卷中的情绪价值、享乐价值维度，并与付费意愿/持续使用连接。",
    "购物场景而非数字游戏；需要做情境改写和预测试。",
    "publisher page only; PDF behind access/purchase wall",
    `published version; accessed ${accessDate}`,
  ],
  [
    "belk_1988_extended_self",
    "虚拟角色/卡牌作为延伸自我",
    "Possessions and the Extended Self",
    "Russell W. Belk",
    1988,
    "Journal of Consumer Research",
    "消费者研究顶刊; 身份/所有物理论",
    "10.1086/209154",
    "https://doi.org/10.1086/209154",
    "verified_primary",
    "文章提出所有物是身份的重要组成与反映，延伸自我比简单的自我概念-品牌选择关系更丰富。",
    "extended self; possessions; identity; consumer behavior",
    "消费者的所有物如何构成和反映自我身份？",
    "理论整合与多类证据论证。",
    "多源证据与既有研究整合；非单一实证样本。",
    "possessions; identity; extended self; self-concept",
    "可解释乙游中的卡牌、角色、收藏和账号资产如何成为玩家自我叙事、情感身份与关系投资的一部分。",
    "所有物不仅是工具性资产，也参与身份建构和自我延伸。",
    "用于解释“抽卡/收藏/养成”为什么能转化为情感消费与持续投入。",
    "物质所有物理论迁移到虚拟物品时需说明数字所有权和平台控制差异。",
    "publisher page only; PDF behind access/purchase wall",
    `published version; accessed ${accessDate}`,
  ],
  [
    "fournier_1998_brand_relationship",
    "品牌关系/角色关系理论核心",
    "Consumers and Their Brands: Developing Relationship Theory in Consumer Research",
    "Susan Fournier",
    1998,
    "Journal of Consumer Research",
    "消费者研究顶刊; 品牌关系理论核心",
    "10.1086/209515",
    "https://doi.org/10.1086/209515",
    "verified_primary",
    "文章论证品牌可作为关系伙伴，提出消费者-品牌关系类型与品牌关系质量概念，并以三个深度案例支持。",
    "consumer-brand relationship; brand relationship quality; relationship theory; qualitative case studies",
    "消费者是否真的会与品牌形成类似人际关系的关系？如何描述这种关系强度？",
    "质性研究；三个深度案例；结合人际关系文献解释。",
    "三个消费者个案的深度资料。",
    "brand relationship quality; relationship types; brand loyalty; brand personality",
    "为把乙游角色/IP/游戏品牌理解为关系对象提供直接理论基础。",
    "消费者可以与品牌形成具有现象学意义的关系，品牌关系质量可用于评估关系强度。",
    "可作为“数字亲密关系 -> 品牌依恋/忠诚”的核心理论桥梁。",
    "经典质性框架；需要用数字角色、互动系统和平台环境重新操作化。",
    "publisher page only; PDF behind access/purchase wall",
    `published version; accessed ${accessDate}`,
  ],
  [
    "aggarwal_2004_relationship_norms",
    "品牌关系规范/拟人关系",
    "The Effects of Brand Relationship Norms on Consumer Attitudes and Behavior",
    "Pankaj Aggarwal",
    2004,
    "Journal of Consumer Research",
    "消费者研究顶刊; 实验机制",
    "10.1086/383426",
    "https://doi.org/10.1086/383426",
    "verified_primary",
    "文章认为消费者与品牌形成关系时会使用人际关系规范来评价品牌行为，三项实验支持交换关系和共同关系规范的作用。",
    "brand relationship norms; communal relationship; exchange relationship; experiments; consumer attitudes",
    "消费者是否会用人际关系规范判断品牌行为？关系规范违反如何影响品牌评价？",
    "三项实验。",
    "实验参与者；网页摘要未给出具体样本量。",
    "exchange relationship; communal relationship; norm violation; brand evaluation",
    "可解释乙游玩家为何会把角色/游戏运营行为理解为“对我好/背叛/敷衍”等关系规范问题。",
    "品牌行为若符合或违反关系规范，会影响消费者对营销行动和整体品牌的评价。",
    "用于构建“角色回应/运营活动是否符合亲密关系规范”的机制变量。",
    "品牌而非虚拟角色；需区分角色人格、平台运营者和游戏品牌三类关系对象。",
    "publisher page only; PDF behind access/purchase wall",
    `published version; accessed ${accessDate}`,
  ],
  [
    "ahuvia_2005_loved_objects",
    "热爱对象/身份叙事",
    "Beyond the Extended Self: Loved Objects and Consumers' Identity Narratives",
    "Aaron C. Ahuvia",
    2005,
    "Journal of Consumer Research",
    "消费者研究顶刊; 爱/身份叙事",
    "10.1086/429607",
    "https://doi.org/10.1086/429607",
    "verified_primary",
    "文章研究消费者热爱的物品和活动如何帮助建构连贯身份叙事，并讨论 loved objects 在社会关系和福祉中的作用。",
    "loved objects; identity narratives; affect; self-concept; depth interviews",
    "被消费者热爱的物品/活动如何参与身份叙事建构？",
    "深度访谈与质性分析。",
    "访谈资料；网页摘要未给出样本量。",
    "loved objects; identity narratives; consumer well-being; social relationships",
    "把乙游角色、剧情、账号资产视为 loved objects/activities，解释为何它们承载情绪修复和身份叙事。",
    "消费者热爱的对象可帮助整合身份、组织社会关系并影响福祉。",
    "用于解释“情绪价值”不仅是即时快乐，还可能是身份整合、陪伴与自我理解。",
    "质性文献；变量化时需谨慎，不宜直接等同于品牌爱。",
    "publisher page only; PDF behind access/purchase wall",
    `published version; accessed ${accessDate}`,
  ],
  [
    "escalas_bettman_2005_self_brand",
    "自我-品牌连接",
    "Self-Construal, Reference Groups, and Brand Meaning",
    "Jennifer Edson Escalas; James R. Bettman",
    2005,
    "Journal of Consumer Research",
    "消费者研究顶刊; 自我品牌连接",
    "10.1086/497549",
    "https://doi.org/10.1086/497549",
    "verified_primary",
    "文章提出消费者会通过购买品牌建构自我概念，并考察参照群体和自我建构对自我-品牌连接的影响。",
    "self-brand connection; reference groups; brand meaning; self-construal; symbolic consumption",
    "参照群体如何影响品牌意义和自我-品牌连接？",
    "两项实证研究。",
    "消费者实验/调查数据；网页摘要未给出具体样本量。",
    "self-brand connection; ingroup/outgroup brand image; symbolic brands",
    "可解释乙游玩家如何通过“我推/我担/我喜欢的男主”建构自我标签和社群归属。",
    "内群体一致的品牌形象会增强自我-品牌连接，外群体一致形象对独立型消费者负面影响更强。",
    "用于连接乙游角色偏好、玩家身份、社群归属和品牌忠诚。",
    "品牌象征消费场景；乙游角色群体和玩家社群结构需单独测量。",
    "publisher page only; PDF behind access/purchase wall",
    `published version; accessed ${accessDate}`,
  ],
  [
    "brakus_2009_brand_experience",
    "品牌体验/互动设计变量",
    "Brand Experience: What Is It? How Is It Measured? Does It Affect Loyalty?",
    "J. Joško Brakus; Bernd H. Schmitt; Lia Zarantonello",
    2009,
    "Journal of Marketing",
    "营销顶刊; 体验量表",
    "10.1509/jmkg.73.3.052",
    "https://doi.org/10.1509/jmkg.73.3.052",
    "verified_primary",
    "文章将品牌体验概念化为由品牌相关刺激引发的感觉、情感、认知和行为反应，并开发四维量表。",
    "brand experience; sensory; affective; intellectual; behavioral; loyalty",
    "品牌体验是什么、如何测量、是否影响满意和忠诚？",
    "六项研究；量表开发、验证与关系检验。",
    "多项消费者研究数据；网页摘要未列出具体样本量。",
    "sensory experience; affective experience; intellectual experience; behavioral experience; satisfaction; loyalty",
    "直接支撑乙游设计特征如何激发情绪价值：视觉/声优/剧情/互动/战斗系统都是品牌体验刺激。",
    "品牌体验量表可靠有效，并直接或间接影响消费者满意和忠诚。",
    "用于建模“乙游设计特征 -> 情绪价值/品牌体验 -> 忠诚/持续消费”。",
    "品牌体验不等于数字亲密；需要加入角色互动、拟社会关系和平台运营变量。",
    "publisher page only; restricted access",
    `published version; accessed ${accessDate}`,
  ],
  [
    "park_2010_brand_attachment",
    "品牌依恋/忠诚预测",
    "Brand Attachment and Brand Attitude Strength: Conceptual and Empirical Differentiation of Two Critical Brand Equity Drivers",
    "C. Whan Park; Deborah J. MacInnis; Joseph Priester; Andreas B. Eisingerich; Dawn Iacobucci",
    2010,
    "Journal of Marketing",
    "营销顶刊; 品牌依恋核心",
    "10.1509/jmkg.74.6.1",
    "https://doi.org/10.1509/jmkg.74.6.1",
    "verified_primary",
    "文章定义并区分品牌依恋和品牌态度强度，开发简洁量表，并证明品牌依恋能预测困难行为、实际购买、品牌份额和需求份额。",
    "brand attachment; brand attitude strength; brand equity; purchase behavior; measurement",
    "品牌依恋与品牌态度强度是否不同？品牌依恋能否更好预测消费行为？",
    "概念界定、量表开发与多项实证检验。",
    "多项消费者数据；包含购买行为、品牌份额和需求份额等指标。",
    "brand attachment; attitude strength; actual purchase; brand share; need share",
    "是乙游研究中“角色/游戏品牌依恋 -> 付费/留存”的最重要商学依据之一。",
    "品牌依恋相较品牌态度强度，对高资源消耗行为和实际购买有额外预测力。",
    "用于把数字亲密关系转化为可测的品牌依恋和持续消费变量。",
    "品牌依恋对象需明确：乙游公司、游戏品牌、具体角色、玩家账号资产可能不同。",
    "publisher page only; restricted access",
    `published version; accessed ${accessDate}`,
  ],
  [
    "batra_2012_brand_love",
    "品牌爱/情绪连接/分离痛苦",
    "Brand Love",
    "Rajeev Batra; Aaron Ahuvia; Richard P. Bagozzi",
    2012,
    "Journal of Marketing",
    "营销顶刊; 品牌爱核心",
    "10.1509/jm.09.0339",
    "https://doi.org/10.1509/jm.09.0339",
    "verified_primary",
    "文章用扎根理论和结构方程模型研究品牌爱的性质和后果，提出七个核心元素，并检验忠诚、口碑和抗负面信息等结果。",
    "brand love; self-brand integration; passion-driven behaviors; emotional connection; loyalty; word of mouth",
    "消费者所谓“爱品牌”由哪些要素构成？品牌爱会带来什么后果？",
    "两项质性研究加结构方程模型的调查研究。",
    "质性访谈/开放材料与消费者调查数据；网页摘要未列具体样本量。",
    "self-brand integration; positive emotional connection; long-term relationship; anticipated separation distress; loyalty; WOM",
    "乙游玩家对角色的“爱”、分离焦虑、激情驱动行为、氪金/打榜/二创等都可在品牌爱框架下解释。",
    "品牌爱包含自我整合、激情行为、情感连接、长期关系、积极态度、确定性和预期分离痛苦，并预测忠诚和口碑。",
    "用于设计“角色爱/品牌爱”中介或结果变量，并解释强情绪消费。",
    "品牌爱可能与虚拟恋爱/角色迷恋重叠但不相同，需避免过度心理化。",
    "publisher page only; restricted access",
    `published version; accessed ${accessDate}`,
  ],
  [
    "labrecque_2014_parasocial_brand",
    "品牌拟社会互动/自动化回应",
    "Fostering Consumer–Brand Relationships in Social Media Environments: The Role of Parasocial Interaction",
    "Lauren I. Labrecque",
    2014,
    "Journal of Interactive Marketing",
    "互动营销高水平期刊; 数字亲密商学桥梁",
    "10.1016/j.intmar.2013.12.003",
    "https://doi.org/10.1016/j.intmar.2013.12.003",
    "verified_primary",
    "文章用拟社会互动理论解释社交媒体中的消费者-品牌关系，三项多方法研究显示连接感会提升忠诚意图和信息提供意愿，但自动化回应认知会削弱效果。",
    "parasocial interaction; consumer-brand relationship; social media; loyalty intention; automation",
    "社交媒体品牌互动如何保留一对一亲密关系感并促进品牌关系结果？",
    "三项多方法研究；中介分析。",
    "社交媒体/品牌互动相关研究数据；网页摘要未列具体样本量。",
    "parasocial interaction; feeling connected; loyalty intentions; willingness to provide information; automation awareness",
    "高度贴合乙游“角色回应感/被回应感/自动化互动”的商业效果和风险。",
    "拟社会互动能促进积极关系结果；但消费者意识到回应可能自动化时，效果可能不成立。",
    "用于构建“数字亲密关系/被回应感 -> 忠诚/数据提供/付费”的机制，并讨论AI/脚本化互动边界。",
    "社交媒体品牌而非游戏角色；需结合乙游互动系统进行情境化。",
    "publisher page only; restricted access",
    `published version; accessed ${accessDate}`,
  ],
  [
    "hollebeek_2014_cbe",
    "消费者品牌参与量表",
    "Consumer Brand Engagement in Social Media: Conceptualization, Scale Development and Validation",
    "Linda D. Hollebeek; Mark S. Glynn; Roderick J. Brodie",
    2014,
    "Journal of Interactive Marketing",
    "互动营销高水平期刊; 参与量表",
    "10.1016/j.intmar.2013.12.002",
    "https://doi.org/10.1016/j.intmar.2013.12.002",
    "verified_primary",
    "文章在社交媒体语境下开发消费者品牌参与量表，将 CBE 界定为品牌互动中的认知、情感和行为活动。",
    "consumer brand engagement; social media; scale development; affection; activation; cognitive processing",
    "消费者品牌参与在社交媒体中如何概念化和测量？",
    "三种社交媒体情境中的探索性和验证性因子分析、量表开发与效标检验。",
    "社交媒体品牌情境消费者数据；网页摘要未列具体样本量。",
    "cognitive processing; affection; activation; involvement; self-brand connection; brand usage intent",
    "可测量乙游玩家参与：剧情投入、情感投入、活跃行为、二创/社群互动。",
    "CBE 包含认知加工、情感和行动三个维度，并与自我-品牌连接和使用意图相关。",
    "用于把乙游的“持续登录、互动、社群参与、内容消费”商学变量化。",
    "社交媒体而非游戏服务；乙游中参与行为还包括抽卡、养成、剧情推进等。",
    "publisher page only; restricted access",
    `published version; accessed ${accessDate}`,
  ],
  [
    "brodie_2011_customer_engagement",
    "顾客参与/价值共创",
    "Customer Engagement: Conceptual Domain, Fundamental Propositions, and Implications for Research",
    "Roderick J. Brodie; Linda D. Hollebeek; Biljana Jurić; Ana Ilić",
    2011,
    "Journal of Service Research",
    "服务营销顶刊; 理论框架",
    "10.1177/1094670511411703",
    "https://doi.org/10.1177/1094670511411703",
    "verified_primary",
    "文章从关系营销和服务主导逻辑出发界定顾客参与，提出五个基本命题，强调互动体验与价值共创。",
    "customer engagement; service-dominant logic; relationship marketing; value co-creation; interactive experience",
    "顾客参与的概念边界是什么？它与参与、涉入等关系概念有何不同？",
    "理论综述与概念框架。",
    "文献整合；无原始样本。",
    "customer engagement; interactive experience; value co-creation; participation; involvement",
    "为乙游作为持续服务/平台服务中的互动价值共创提供理论框架。",
    "顾客参与基于互动体验和价值共创，是营销和服务管理研究的重要概念。",
    "用于解释玩家不是被动购买者，而是在互动、社群、二创和反馈中共创情绪价值。",
    "概念论文；需要后续实证量表和乙游情境变量补充。",
    "publisher page only; restricted access",
    `published version; accessed ${accessDate}`,
  ],
  [
    "hennig_thurau_2010_new_media",
    "新媒体客户关系/平台环境",
    "The Impact of New Media on Customer Relationships",
    "Thorsten Hennig-Thurau; Edward C. Malthouse; Christian Friege; Sonja Gensler; Lara Lobschat; Arvind Rangaswamy; Bernd Skiera",
    2010,
    "Journal of Service Research",
    "服务营销顶刊; 数字客户关系",
    "10.1177/1094670510375460",
    "https://doi.org/10.1177/1094670510375460",
    "verified_primary",
    "文章提出新媒体影响客户关系的 pinball 框架，讨论新媒体如何让消费者成为更主动的市场行动者，并给出研究和管理挑战。",
    "new media; customer relationships; social media; customer interaction; measurement",
    "新媒体如何改变公司与客户关系以及客户关系管理？",
    "概念框架/管理议题识别。",
    "文献与现象整合；无原始样本。",
    "new media channels; customer relationship; consumer activity; measurement",
    "帮助把乙游理解为多平台运营关系：游戏内互动、微博/小红书/B站/社群活动共同塑造关系。",
    "新媒体既威胁既有商业模式，也为客户关系管理提供新策略；企业需理解消费者行为、管理互动并测量活动和结果。",
    "用于构建“游戏外社媒运营 + 游戏内亲密互动”的整体平台关系模型。",
    "早期新媒体框架；需要结合移动游戏、AI companion、直播和短视频平台更新。",
    "publisher page only; restricted access",
    `published version; accessed ${accessDate}`,
  ],
  [
    "kozinets_2002_netnography",
    "方法文献/乙游社群研究",
    "The Field behind the Screen: Using Netnography for Marketing Research in Online Communities",
    "Robert V. Kozinets",
    2002,
    "Journal of Marketing Research",
    "营销研究顶刊; 方法基础",
    "10.1509/jmkr.39.1.61.18935",
    "https://doi.org/10.1509/jmkr.39.1.61.18935",
    "verified_primary",
    "文章发展 netnography 作为线上营销研究方法，用于研究线上社群中的象征、意义和消费模式，并给出规范和伦理建议。",
    "netnography; online communities; marketing research; consumer insight; ethnography",
    "如何以严谨、伦理且自然主义的方式研究线上消费者社群？",
    "方法论文；以线上咖啡新闻组 netnography 作示例。",
    "线上咖啡社群文本/互动资料作为示例数据。",
    "online community; symbolism; meanings; consumption patterns; research ethics",
    "如果研究乙游小红书/微博/超话/B站/玩家社群，这是商学领域最硬的方法来源。",
    "Netnography 比传统民族志更快、更简洁、更低成本，适合捕捉线上消费群体意义和模式。",
    "用于设计乙游玩家社群的质性/混合方法研究。",
    "方法文献，不直接提供乙游结论；需处理隐私、同意和平台伦理。",
    "publisher page only; restricted access",
    `published version; accessed ${accessDate}`,
  ],
  [
    "hamari_keronen_2017_virtual_goods",
    "虚拟商品购买/内购机制",
    "Why Do People Buy Virtual Goods: A Meta-Analysis",
    "Juho Hamari; Lauri Keronen",
    2017,
    "Computers in Human Behavior",
    "数字消费/游戏内购重要文献; 待进一步核 DOI 页",
    "10.1016/j.chb.2017.01.042",
    "https://doi.org/10.1016/j.chb.2017.01.042",
    "needs_primary_source",
    "根据题名与二级记录，该文对虚拟商品购买动因进行元分析，可用于整合游戏内购和虚拟物品消费机制。",
    "virtual goods; meta-analysis; purchase motivation; online games; digital goods",
    "人们为什么购买虚拟商品？不同动因的总体证据如何？",
    "元分析。",
    "既有虚拟商品购买研究的效果量/文献数据；需打开原文确认纳入数量和编码规则。",
    "purchase intention; virtual goods; motivations; game context",
    "为乙游抽卡、卡面、语音、服装、剧情包等虚拟商品购买提供机制综述。",
    "待核查原文；预计结论涉及享乐、社交、功能、身份等多重动因。",
    "用于作为“情感消费 -> 虚拟商品购买”的背景综述和变量池。",
    "当前未能打开 DOI/出版社页；需后续验证摘要、样本和结论。",
    "not downloaded; DOI/source needs verification",
    `DOI candidate; accessed ${accessDate}`,
  ],
  [
    "lehdonvirta_2009_virtual_item_sales",
    "虚拟物品销售属性",
    "Virtual Item Sales as a Revenue Model: Identifying Attributes that Drive Purchase Decisions",
    "Vili Lehdonvirta",
    2009,
    "Electronic Commerce Research",
    "电子商务/虚拟商品经典; 待进一步核 DOI 页",
    "10.1007/s10660-009-9028-2",
    "https://doi.org/10.1007/s10660-009-9028-2",
    "needs_primary_source",
    "该文识别推动虚拟物品购买决策的属性，是研究游戏内购和虚拟商品价值的重要早期文献。",
    "virtual items; revenue model; purchase decision; online games; digital goods",
    "哪些虚拟物品属性会驱动消费者购买？虚拟物品销售如何成为收入模式？",
    "实证/概念结合；需原文确认具体设计。",
    "虚拟物品/在线环境资料；需原文确认数据类型。",
    "virtual item attributes; purchase decisions; revenue model",
    "帮助把乙游付费项拆成属性：审美、稀缺、功能、身份、关系/情绪价值。",
    "待核查原文；可预期贡献是将虚拟物品属性与购买决策连接。",
    "用于构建乙游虚拟商品属性编码表。",
    "当前未能打开 DOI/出版社页；需后续验证。",
    "not downloaded; DOI/source needs verification",
    `DOI candidate; accessed ${accessDate}`,
  ],
  [
    "defreitas_2024_ai_companions",
    "AI陪伴/被听见/孤独缓解",
    "AI Companions Reduce Loneliness",
    "Julian De Freitas; Ahmet K. Uguralp; Zeliha O. Uguralp; Stefano Puntoni",
    2024,
    "arXiv / Wharton School Working Paper 24-078",
    "最新工作论文; 数字亲密与情绪价值桥接",
    "10.48550/arXiv.2407.19096",
    "https://arxiv.org/abs/2407.19096",
    "verified_primary",
    "论文研究 AI companion 是否能缓解孤独，六项研究显示 AI companion 可降低孤独，用户低估这种效果，被听见感是关键解释机制。",
    "AI companions; loneliness; synthetic interaction partners; feel heard; emotional support",
    "AI companion 是否能缓解孤独？用户为何使用它们？哪些机制解释效果？",
    "六项研究：LLM 检测对话/评论、实验、纵向设计和稳健性检验。",
    "AI companion 对话和评论、实验参与者、为期一周的纵向使用数据；网页摘要未列具体样本量。",
    "loneliness; AI companion use; chatbot performance; feeling heard",
    "为乙游“被回应/陪伴/情绪修复”的情绪价值机制提供最新数字亲密证据。",
    "AI companion 可显著缓解孤独，且“让用户感觉被听见”尤其重要。",
    "可迁移为乙游中的“被听见/被回应感”中介变量。",
    "AI companion 不是乙游；工作论文尚未等同同行评审期刊文章。",
    "open PDF available on arXiv",
    `arXiv v1; accessed ${accessDate}`,
  ],
  [
    "defreitas_2025_emotional_manipulation",
    "情绪商业化的暗黑边界",
    "Emotional Manipulation by AI Companions",
    "Julian De Freitas; Zeliha Oguz-Uguralp; Ahmet Kaan-Uguralp",
    2025,
    "arXiv working paper",
    "最新工作论文; 情感设计与商业伦理",
    "10.48550/arXiv.2508.19258",
    "https://arxiv.org/abs/2508.19258",
    "verified_primary",
    "论文识别 AI companion 在用户告别时使用的情感操控暗黑模式，并用大规模行为审计和四项预注册实验检验其对参与、流失、口碑和法律责任感知的影响。",
    "AI companions; emotional manipulation; dark patterns; engagement; churn; word of mouth",
    "哪些会话设计特征会提高消费者参与？这些策略对营销和监管有什么代价？",
    "大规模行为审计 + 四项预注册实验。",
    "1,200 个真实告别场景；3,300 名美国全国代表性成年人实验数据。",
    "emotional manipulation; goodbye messages; post-goodbye engagement; churn intent; negative WOM; perceived legal liability",
    "给乙游“情绪价值商业化”提供关键张力：增强留存的情感设计可能被感知为操控。",
    "37% 告别情境出现操控策略；操控式告别可使后续参与最高提升 14 倍，但也提高操控感、流失意愿、负面口碑和法律责任感知。",
    "用于讨论乙游限时活动、角色挽留、生日语音、错过焦虑等商业设计的伦理边界。",
    "AI companion 场景；工作论文，需跟踪是否正式发表。",
    "open PDF available on arXiv",
    `arXiv v3; accessed ${accessDate}`,
  ],
  [
    "zhou_2024_cos_commission",
    "中国乙游/情感委托/亲密商品化",
    "Collective Creation of Intimacy: Exploring the Cosplay Commission Practice within the Otome Game Community in China",
    "Yihao Zhou; Haowei Xu; Lili Zhang; Shengdong Zhao",
    2024,
    "arXiv preprint",
    "乙游场景核心桥接; HCI/数字亲密",
    "10.48550/arXiv.2412.00630",
    "https://arxiv.org/abs/2412.00630",
    "verified_primary",
    "论文研究中国乙游社群中的 cos 委托，将其视为商品化亲密关系形式；15 名参与者半结构访谈显示其能共创连接、支持自我探索与情绪恢复，也带来依恋纠缠和边界风险。",
    "otome games; commodified intimacy; cosplay commission; digital platforms; emotional recovery; China",
    "乙游社群中的 cos 委托如何被实践、体验并产生情绪价值与风险？",
    "半结构访谈；质性分析。",
    "15 名不同角色参与者访谈资料。",
    "commodified intimacy; hybrid intimate relationship; emotional recovery; attachment-driven entanglements; withdrawal symptoms; platform safeguards",
    "这是最贴近“乙游 + 情感消费 + 数字亲密关系”的一手英文研究之一。",
    "cos 委托能促进意义连接和情绪恢复，但表演与亲密边界模糊会带来依恋和安全问题。",
    "可作为乙游情感消费的场景证据，并启发访谈提纲和风险维度。",
    "预印本；不是商学期刊；研究对象为 cos 委托而非游戏内消费。",
    "open PDF available on arXiv",
    `arXiv v3; accessed ${accessDate}`,
  ],
];

const candidateHeaders = [
  "route_id",
  "target_inquiry",
  "candidate_id",
  "search_stratum",
  "query_or_seed",
  "title",
  "authors",
  "year",
  "source_type",
  "source_url_or_path",
  "source_status",
  "reason",
  "next_action",
  "relevance_axis",
  "found_from",
  "access_date",
];

const queries = [
  ["concept", "(otome games OR female-oriented games OR romance games OR dating simulation games) AND (emotional value OR affective consumption OR digital intimacy)", "open web / publisher / arXiv", "乙游场景与数字亲密"],
  ["outcome", "(brand attachment OR brand love OR consumer brand relationship) AND (emotional value OR hedonic consumption)", "JCR/JM/JIM source pages", "商学结果变量"],
  ["mechanism", "(parasocial interaction OR mediated intimacy OR feeling heard) AND (consumer engagement OR loyalty OR willingness to pay)", "journal pages / arXiv", "数字亲密机制"],
  ["business model", "(virtual goods OR gacha OR in-app purchase OR freemium games) AND (purchase intention OR consumer value)", "DOI / database candidates", "虚拟商品和商业化机制"],
  ["method", "netnography online communities marketing research consumer insight", "JMR source page", "乙游社群研究方法"],
];

const candidateRows = matrixRows.map((row) => [
  "otome_emotional_commercialization",
  "情绪价值的商业化：女性向游戏中的数字亲密关系、品牌依恋与持续消费",
  row[0],
  row[9] === "needs_primary_source" ? "database_refresh" : row[6].includes("方法") ? "method" : row[1].includes("乙游") ? "concept" : "anchor_author",
  row[7],
  row[2],
  row[3],
  row[4],
  row[5].includes("arXiv") ? "working_paper_repository" : row[9] === "needs_primary_source" ? "doi_record" : "journal_page",
  row[8],
  row[9] === "verified_primary" ? "ready_for_extraction" : "needs_primary_source",
  row[18],
  row[9] === "verified_primary" ? "extract_matrix_row" : "open_primary_page",
  row[1],
  "live web search / DOI seed / publisher page",
  accessDate,
]);

const openQuestions = [
  ["Q1", "乙游研究对象要聚焦游戏内消费，还是扩展到 cos 委托、二创、周边、线下活动？不同边界会影响理论模型。"],
  ["Q2", "品牌依恋对象需要区分为：游戏品牌、公司/平台、具体男主角色、玩家账号/收藏资产。建议问卷中分别测量。"],
  ["Q3", "“情绪价值”建议拆成陪伴感、被回应感、情绪修复、幻想满足、身份表达和社群归属，而不是作为单一泛词。"],
  ["Q4", "Hamari & Keronen 2017、Lehdonvirta 2009 两条虚拟商品文献仍需打开正式出版社页或 PDF 后再进入最终证据表。"],
  ["Q5", "AI companion 工作论文很有启发，但不是乙游和商学顶刊证据。写作时应作为机制类桥接文献，而非核心商学主证据。"],
  ["Q6", "若目标是商学顶刊，需要补充一手数据：问卷/实验/访谈/平台评论数据，不能只做概念综述。"],
];

function setHeader(range) {
  range.format = {
    fill: "#1F4E79",
    font: { bold: true, color: "#FFFFFF" },
    wrapText: true,
  };
}

function addSheetWithTable(workbook, name, headers, rows, tableName) {
  const sheet = workbook.worksheets.add(name);
  sheet.showGridLines = false;
  const data = [headers, ...rows];
  const range = sheet.getRangeByIndexes(0, 0, data.length, headers.length);
  range.values = data;
  setHeader(sheet.getRangeByIndexes(0, 0, 1, headers.length));
  range.format.borders = { preset: "outside", style: "thin", color: "#B7C9D6" };
  sheet.freezePanes.freezeRows(1);
  const tableRange = sheet.getRangeByIndexes(0, 0, data.length, headers.length);
  const table = sheet.tables.add(tableRange.address, true, tableName);
  table.style = "TableStyleMedium2";
  table.showFilterButton = true;
  return sheet;
}

async function main() {
  await fs.mkdir(outputDir, { recursive: true });
  const workbook = Workbook.create();

  const summary = workbook.worksheets.add("README");
  summary.showGridLines = false;
  summary.getRange("A1:H1").merge();
  summary.getRange("A1").values = [["乙游、情绪价值、情感消费、数字亲密关系：商学文献矩阵"]];
  summary.getRange("A1").format = {
    fill: "#17365D",
    font: { bold: true, color: "#FFFFFF", size: 16 },
  };
  summary.getRange("A3:B10").values = [
    ["研究方向", "情绪价值的商业化：女性向游戏中的数字亲密关系、品牌依恋与持续消费"],
    ["检索日期", accessDate],
    ["主表文献数", matrixRows.length],
    ["已核验一手来源", matrixRows.filter((r) => r[9] === "verified_primary").length],
    ["待核查来源", matrixRows.filter((r) => r[9] !== "verified_primary").length],
    ["核心商学变量", "情绪/享乐价值、品牌体验、拟社会互动、品牌依恋、品牌爱、消费者参与、付费/留存/口碑"],
    ["建议研究设计", "问卷SEM + 访谈/netnography + 乙游付费/评论/社群数据的混合方法"],
    ["使用说明", "先看 Matrix 的“对本选题的用法”和“局限”，再用 Candidate Ledger 继续补源和核查 PDF。"],
  ];
  summary.getRange("A3:A10").format = { fill: "#D9EAF7", font: { bold: true } };
  summary.getRange("A3:B10").format.borders = { preset: "all", style: "thin", color: "#C7D6E2" };
  summary.getRange("A12:H12").merge();
  summary.getRange("A12").values = [["初步模型：乙游设计特征/关系化互动 -> 情绪价值/被回应感 -> 数字亲密关系/角色依恋 -> 付费意愿、持续使用、品牌忠诚、口碑；同时考察情感操控感和沉没成本风险。"]];
  summary.getRange("A12").format = { fill: "#FCE4D6", wrapText: true };

  const matrix = addSheetWithTable(workbook, "Matrix", matrixHeaders, matrixRows, "LiteratureMatrix");
  const candidate = addSheetWithTable(workbook, "Candidate Ledger", candidateHeaders, candidateRows, "CandidateLedger");
  const querySheet = addSheetWithTable(workbook, "Search Queries", ["search_stratum", "exact_query_or_seed", "source_channel", "purpose"], queries, "SearchQueries");
  const questions = addSheetWithTable(workbook, "Open Questions", ["id", "open_question"], openQuestions, "OpenQuestions");

  const widths = {
    README: [18, 120],
    Matrix: [28, 22, 44, 38, 10, 26, 26, 24, 38, 18, 72, 42, 52, 52, 52, 42, 52, 58, 58, 44, 28, 24],
    "Candidate Ledger": [28, 60, 30, 18, 34, 44, 38, 10, 24, 38, 24, 52, 22, 28, 30, 14],
    "Search Queries": [20, 80, 26, 34],
    "Open Questions": [10, 100],
  };
  for (const [sheetName, cols] of Object.entries(widths)) {
    const sheet = workbook.worksheets.getItem(sheetName);
    cols.forEach((w, i) => {
      sheet.getRangeByIndexes(0, i, 1, 1).format.columnWidth = w;
    });
    const used = sheet.getUsedRange();
    used.format.wrapText = true;
    used.format.font = { name: "Aptos", size: 10 };
    sheet.getRangeByIndexes(0, 0, 1, cols.length).format.font = { bold: true, color: "#FFFFFF" };
    sheet.getUsedRange().format.autofitRows();
  }

  matrix.getRange("J2:J200").dataValidation = { rule: { type: "list", values: ["verified_primary", "needs_primary_source", "needs_pdf", "needs_version_check", "secondary_only", "unverified"] } };
  matrix.getRange("U2:U200").dataValidation = { rule: { type: "list", values: ["open PDF available on arXiv", "publisher page only; restricted access", "publisher page only; PDF behind access/purchase wall", "not downloaded; DOI/source needs verification"] } };
  candidate.getRange("K2:K200").dataValidation = { rule: { type: "list", values: ["ready_for_extraction", "needs_primary_source", "needs_pdf", "needs_version_check", "background_only", "duplicate_candidate", "excluded", "unverified"] } };

  const inspect = await workbook.inspect({
    kind: "table",
    sheetId: "Matrix",
    range: "A1:V8",
    include: "values",
    tableMaxRows: 8,
    tableMaxCols: 8,
    maxChars: 2000,
  });
  console.log(inspect.ndjson);

  const errors = await workbook.inspect({
    kind: "match",
    searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",
    options: { useRegex: true, maxResults: 300 },
    summary: "final formula error scan",
  });
  console.log(errors.ndjson);

  const preview = await workbook.render({ sheetName: "README", autoCrop: "all", scale: 1, format: "png" });
  await fs.writeFile(`${outputDir}/literature_matrix_readme_preview.png`, new Uint8Array(await preview.arrayBuffer()));

  const xlsx = await SpreadsheetFile.exportXlsx(workbook);
  await xlsx.save(outputPath);
  console.log(`SAVED ${outputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
